### ISSUE TITLE
能解析秒拍视频的真实下载地址吗？

### ISSUE THREAD

**Issue by NanyangTaiji** [CynanC/Miaopai-Name-Checker#1]

**Comment by CynanC** [comment]
这个程序不能的，只能检查视频的名字是否符合规则，真实下载地址你可以用下列的代码解析
`import re
import requests
import json

m = re.search(r'/show/([\w~-]+)\.htm', 'http://www.miaopai.com/show/Qo3uI72UKWF-EriUFLL~VA__.htm')
vid = m.group(1)
r = requests.get('http://gslb.miaopai.com/stream/%s.json?token=' % vid)
data = json.loads(r.content)
urls = [r['scheme'] + r['host'] + r['path'] for r in data['result']]
print(urls[0])`

**Comment by NanyangTaiji** [comment]
谢谢。

我的秒拍地址前都加了个n
http://n.miaopai.com/media/USKaALx~jQapSKtuYCQbOhcnbSGslAf4.htm
